# Site Settings
locale                   : "en-US"
title                    : "13:20:Sync"
title_separator          : "|"
name                     : "13:20:Sync"
description              : "This app clarifies key aspects of the Law of Time and provides a simple way to sync along the cosmic cycles."
url                      : "https://www.1320sync.com/"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : ""
destination              : "../1320syncwebsite"
markdown: kramdown
plugins:
  - jekyll-feed

collections:
  - features
  - reviews


teaser                   : "https://www.1320sync.com/images/page_large_image.png" # path of fallback teaser image, e.g. "/assets/images/500x300.png"
# breadcrumbs            : false # true, false (default)
words_per_minute         : 200

search_provider          : # lunr (default), algolia, google
algolia:
  application_id         : # YOUR_APPLICATION_ID
  index_name             : # YOUR_INDEX_NAME
  search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : # true (default), false
google:
  search_engine_id       : # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (default), true
# SEO Related
google_site_verification :
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :
alexa_site_verification  :

# Social Sharing
twitter:
  username               :
facebook:
  username               : "@1320sync"
  app_id                 :
  publisher              :
og_image                 : "https://www.1320sync.com/images/page_large_image.png" # Open Graph/Twitter default site image

# Analytics
analytics:
  provider               : "google-universal" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : UA-2812394-1
    anonymize_ip         : # true, false (default)


